# Generated by Django 4.1.3 on 2022-12-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='webapp.products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='remains',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
